---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/agent
    tag: go1.8.3

inputs:
- name: bosh-agent
  path: gopath/src/github.com/cloudfoundry/bosh-agent
- name: version-semver

outputs:
- name: compiled-linux-amd64-go-1.8

params:
  DIRNAME: compiled-linux-amd64-go-1.8
  GOVERSION: go-1.8
  GOARCH: amd64
  GOOS:   linux

run:
  path: gopath/src/github.com/cloudfoundry/bosh-agent/ci/tasks/build.sh
